variables:
  UNIT_TEST_FOLDER: '.\SudokuTest\'
stages:
  - build
  - unit test
  - test

build_job:
  tags:
    - MSBuild
  stage: build
  script:
    - msbuild -p:PlatformToolset=v141 -p:WindowsTargetPlatformVersion= -p:Configuration=Release
  artifacts:
    expire_in: 1 week
    paths:
      - '.\x64\Release\Sudoku.exe'


unit_test_job:
  tags: 
    - MSBuild
  stage: unit test
  script:
    - cd Sudoku
    # 编译静态链接库用于单元测试
    - msbuild -p:PlatformToolset=v141 -p:WindowsTargetPlatformVersion= -p:Configuration=Release -p:ConfigurationType=StaticLibrary
    - cd ..
    - cd "$UNIT_TEST_FOLDER"
    - msbuild -p:PlatformToolset=v141 -p:WindowsTargetPlatformVersion= -p:Configuration=Release -p:ConfigurationType=DynamicLibrary
    - cd Release
    - vstest.console SudokuTest.dll

test_job:
  tags:
    - MSBuild
  stage: test
  script:
    - mkdir bin
    - mv .\x64\Release\Sudoku.exe bin\
    - SudokuAutoTest -number "$GITLAB_USER_LOGIN"
  dependencies:
    - build_job