variables:
  PROJECT_NAME: $CI_PROJECT_NAME
  UNIT_TEST_NAME: 'SudokuTest'
  PWD: $CI_PROJECT_DIR
  OUTPUT: $CI_PROJECT_DIR\bin

stages:
  - report_start
  - build
  - test
  - report_end

before_script:
  - chcp 65001

build_job:
  tags:
    - MSBuild
  stage: build
  script:
    - msbuild -p:OutDir=%OUTPUT%;PlatformToolset=v141;WindowsTargetPlatformVersion=10.0.17134.0;Configuration=Release
  artifacts:
    expire_in: 1 week
    paths:
      - "%OUTPUT%\\%PROJECT_NAME%.exe"


unit_test_job:
  tags: 
    - MSBuild
  stage: test
  script:
    - cd %PROJECT_NAME%
    # 编译静态链接库用于单元测试
    - msbuild -p:OutDir=%OUTPUT%;PlatformToolset=v141;WindowsTargetPlatformVersion=10.0.17134.0;Configuration=Release;ConfigurationType=StaticLibrary
    - cd ..
    - cd %UNIT_TEST_NAME%
    - msbuild -p:OutDir=%OUTPUT%;PlatformToolset=v141;WindowsTargetPlatformVersion=10.0.17134.0;Configuration=Release;ConfigurationType=DynamicLibrary
    - cd %OUTPUT%
    - vstest.console %UNIT_TEST_NAME%.dll /logger:trx;verbosity=minimal;LogFileName=unittest.trx /ResultsDirectory:.\
    - move unittest.trx %PWD%
  artifacts:
    paths:
      - "%PWD%\\unittest.trx"
      
test_job:
  tags:
    - MSBuild
  stage: test
  script:
    - SudokuAutoTest -number %GITLAB_USER_LOGIN%
  dependencies:
    - build_job
  artifacts:
    expire_in: 1 week
    paths:
      - score.json

report_start_job:
  tags:
    - MSBuild
  stage: report_start
  script:
    - AutoTestReport -s

report_end_job:
  tags:
    - MSBuild
  stage: report_end
  script:
    - AutoTestReport -f score.json -u unittest.trx
  when: always
  retry:  3
  dependencies:
    - unit_test_job
    - test_job