variables:
  PROJECT_NAME: 'Sudoku'
  UNIT_TEST_NAME: 'SudokuTest'
  PWD: $CI_PROJECT_DIR
  # OUTPUT: $CI_PROJECT_DIR\bin
  OUTPUT: ${PWD}\bin

stages:
  - build
  - unit test
  - test

before_script:
  - chcp 65001
  - echo %PWD%
  - echo %OUTPUT%

build_job:
  tags:
    - MSBuild
  stage: build
  script:
    - msbuild -p:OutDir=%OUTPUT%;PlatformToolset=v141;WindowsTargetPlatformVersion=10.0.17134.0;Configuration=Release
  artifacts:
    expire_in: 1 week
    paths:
      - "%OUTPUT%\\%PROJECT_NAME%.exe"


unit_test_job:
  tags: 
    - MSBuild
  stage: unit test
  script:
    - cd %PROJECT_NAME%
    # 编译静态链接库用于单元测试
    - msbuild -p:OutDir=%OUTPUT%;PlatformToolset=v141;WindowsTargetPlatformVersion=10.0.17134.0;Configuration=Release;ConfigurationType=StaticLibrary
    - cd ..
    - cd %UNIT_TEST_NAME%
    - msbuild -p:OutDir=%OUTPUT%;PlatformToolset=v141;WindowsTargetPlatformVersion=10.0.17134.0;Configuration=Release;ConfigurationType=DynamicLibrary
    - cd %OUTPUT%
    - vstest.console %UNIT_TEST_NAME%.dll

test_job:
  tags:
    - MSBuild
  stage: test
  script:
    - SudokuAutoTest -number %GITLAB_USER_LOGIN%
  dependencies:
    - build_job